###### DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-noticias-deployment
######

###### Definição das REPLICAS
spec:
  replicas: 1
######

###### Definição dos PODS
  template:
    metadata:
      name: db-noticias
      labels:
        app: db-noticias
######

###### Definição dos CONTAINERS
    spec:
      containers:
        - name: db-noticias-container
          image: aluracursos/db-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: db-configmap
######

##### Vinculando o DEPLOYMENT ao POD
  selector:
    matchLabels:
      app: db-noticias
#####