##### DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias-deployment
#####

##### Definição das REPLICAS
spec:
  replicas: 3
#####

##### Definição dos PODS
  template:
    metadata:
      name: portal-noticias
      labels:
        app: portal-noticias #label
#####

##### Defnição dos CONTAINERS
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80 #porta que o container escuta
          envFrom:
            - configMapRef:
                name: portal-configmap
#####

##### Vinculando o DEPLOYMENT ao POD
  selector: 
    matchLabels:
      app: portal-noticias
#####